### ISSUE TITLE
TemplateDoesNotExist at /admin/ admin/login.html

### ISSUE THREAD

**Issue by pxg** [wunki/django-salted#1]
Hello, I've been following the steps in the README, the vagrant pox has installed and provisioned but when I go to http://127.0.0.1:8080/admin/ I get the error:

```
Exception Type: TemplateDoesNotExist
Exception Value:    
admin/login.html
Exception Location: /home/vagrant/env/local/lib/python2.7/site-packages/django/template/loader.py in find_template, line 139
Python Executable:  /usr/local/bin/uwsgi
```

Will try and workout what's going wrong and report back. I set-up demo_project outside of vagrant (on OS X) and it worked fine.

**Comment by pxg** [comment]
```
sudo pip uninstall Django
pip install Django
sudo service uwsgi restart
```

This solved it but I'm still curious why it was broken in the first place.

**Comment by wunki** [comment]
Yes, I think this is caused by wheel. Maybe it's not copying the Django templates?

**Comment by pxg** [comment]
Ah ok, I don't have much experience with wheel, I'll take a look into that and see if I can work out a fix.
