### ISSUE TITLE
'fab' is currently not installed

### ISSUE THREAD

**Issue by zot24** [wunki/django-salted#11]
After run the next command `fab vagrant syncdb` I receive the following message:

```
The program fab is currently not installed.  You can install it by typing:
sudo apt-get install fabric
```

Should be `fab` installed after run the command `vagrant up`?

**Comment by tomleo** [comment]
You must install fabric on your host machine, not the guest VM managed by vagrant. 

Doing a `pip install -r requirements` on your host machine should install fabric for you.

**Comment by wunki** [comment]
Yes, that should indeed do it. You need `fabric` python package to rub `fab` commands.

**Comment by zot24** [comment]
Cheers guys!
