### ISSUE TITLE
wheel + setuptools

### ISSUE THREAD

**Issue by Ameriks** [wunki/django-salted#4]
Hello,
When executing command "vagrant up", I can see several errors.

Command: "/home/vagrant/env/bin/pip install --use-wheel --no-index --find-links=/home/vagrant/wheel/example -r /vagrant/demo_project/requirements.txt"

Result:
Ignoring indexes: https://pypi.python.org/simple/
setuptools==0.8dev,>=0.8b2 is required for wheel installs.
pip's wheel support requires setuptools==0.8dev,>=0.8b2.

How can I get setuptools version 0.8b2 ?

Thanks!

**Comment by wunki** [comment]
Yes, wheel jumped the shark on an update. I will be removing it from the equation in the next commit.

**Comment by wunki** [comment]
Fixed in f5e29eece7594e4ddb204ff96d73802110ddad9b
