### ISSUE TITLE
Installation with Debian Wheezy

### ISSUE THREAD

**Issue by saintger** [wunki/django-salted#6]
I wanted to try with Debian Wheezy, so I generated a Debian Wheezy Vagrant box using this:
http://stacktoheap.com/blog/2013/06/19/building-a-debian-wheezy-vagrant-box-using-veewee/

I only add to install 3 more packages into this box: python-pip, python-dev, uwsgi
I also needed to modify the /etc/apt/sources.list to add:
deb http://debian.saltstack.com/debian wheezy-saltstack main

After that I modified Vagrantfile to specify this box and to remove the salt.install_type = "daily" (which is specific to Ubuntu).

I ran "vagrant up" and everything was frozen during the "setting hostname". So I manually changed the hostname and everything went fine until the end.

However I cannot access the website (502 Bad Gateway).

Here is the error message by uwsgi:
Fri Jul 26 00:32:56 2013 - -- unavailable modifier requested: 0 --

And here is the error message by nginx:
2013/07/26 00:32:56 [error] 18072#0: *6 upstream prematurely closed connection while reading response header from upstream, client: 10.0.2.2, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:3000", host: "127.0.0.1:8080"

I don't know why it doesn't work ? I don't have any more clue.

**Comment by saintger** [comment]
Ok found the mistake: I also had to apt-get uwsgi-plugin-python.

So except for the hostname changing problem, I am happy to announce that this is compatible with Debian Wheezy ! ;-)

**Comment by wunki** [comment]
Thanks for the heads up. I would be possible to modify the states and put some `{% if %}` in there for Debian specific packages. I currently don't have the time to do it though.
