### ISSUE TITLE
failing to boot

### ISSUE THREAD

**Issue by kwilsbach** [wunki/django-salted#8]
I understand this may be more MY issue than an issue with django-salted.

I recently set up a new ubuntu 12.04 server and am attempting to make better use of the space for development.

sudo vagrant up
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.
Bringing machine 'web' up with 'virtualbox' provider...
[web] Clearing any previously set forwarded ports...
[web] Creating shared folders metadata...
[web] Clearing any previously set network interfaces...
[web] Preparing network interfaces based on configuration...
[web] Forwarding ports...
[web] -- 22 => 2222 (adapter 1)
[web] -- 80 => 8080 (adapter 1)
[web] Running 'pre-boot' VM customizations...
[web] Booting VM...
[web] Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

my research into the issue has primarily lead to "downgrade virtualbox" and I have, to 4.1.26, while before i was using 4.2.18 and getting the same results. I'm wondering if my issues are merely server set up, or incompatibilities with vagrant, virtualbox, and django-salted settings?

**Comment by wunki** [comment]
This seems to be a problem with virtualbox. Don't think this is an incompatibilty with django-salted because the `salt` command is not run yet.
