### ISSUE TITLE
This master address: 'salt' was previously resolvable but now fails to resolve!

### ISSUE THREAD

**Issue by romantolkachyov** [wunki/django-salted#9]
When I do "vagrant up" it fails with:

[INFO    ] Package bash is already installed
[ERROR   ] This master address: 'salt' was previously resolvable but now fails to resolve! The previously resolved ip addr will continue to be used
Minion failed to authenticate with the master, has the minion key been accepted?
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

salt-call state.highstate -l debug

**Comment by wunki** [comment]
I don't know if this is a problem with `django-salted`. Could you try running the above manually?

```
vagrant ssh
sudo salt-call state.highstate -l debug
```
